FROM python
# Diretorio que o container inicia logado
WORKDIR /usr/src/app
# Copia app.py do diretório atual para o destino /usr/src/app
COPY app.py /usr/src/app
# Executa o app.py
CMD ["python", "./app.py"]
